In [1]:
liked_books = ['4408', '31147619', '5996629', '28765183', '8132407', '31147619', '20494944']

In [2]:
!head book_id_map.csv

book_id_csv,book_id
0,34684622
1,34536488
2,34017076
3,71730
4,30422361
5,33503613
6,33517540
7,34467031
8,6383669

In [10]:
csv_book_mapping = {}
with open('book_id_map.csv', 'r') as f:
    while True:
        line = f.readline()
        if not line:
            break
        csv_id, book_id = line.strip().split(',')
        csv_book_mapping[csv_id] = book_id

In [11]:
len(csv_book_mapping)

2360651

In [12]:
!wc -l goodreads_interactions.csv

 228648343 goodreads_interactions.csv

In [13]:
!ls -lh | grep goodreads_interactions.csv

-rw-r--r--@ 1 abdullahalmomin  staff   4.0G Jun  7 11:14 goodreads_interactions.csv

In [14]:
!head goodreads_interactions.csv

user_id,book_id,is_read,rating,is_reviewed
0,948,1,5,0
0,947,1,5,1
0,946,1,5,0
0,945,1,5,0
0,944,1,5,0
0,943,1,5,0
0,942,1,5,0
0,941,1,5,0
0,940,1,5,0

In [15]:
overlap_users = set()

with open('goodreads_interactions.csv', 'r') as f:
    while True:
        line = f.readline()
        if not line:
            break
        user_id, csv_id, _, ratings, _ = line.split(',')
        
        if user_id in overlap_users:
            continue
        
        try:
            ratings = int(ratings)
        except ValueError:
            continue
            
        book_id = csv_book_mapping[csv_id]
        
        if book_id in liked_books and ratings >= 4:
            overlap_users.add(user_id)

In [16]:
rec_line = []
with open('goodreads_interactions.csv', 'r') as f:
    while True:
        line = f.readline()
        if not line:
            break
        user_id, csv_id, _, ratings, _ = line.split(',')
        
        if user_id in overlap_users:
            book_id = csv_book_mapping[csv_id]
            rec_line.append([user_id, book_id, ratings])

In [27]:
len(overlap_users)

903

In [19]:
len(rec_line)

533722

In [18]:
import pandas as pd

recs = pd.DataFrame(rec_line, columns=['user_id', 'book_id', 'ratings'])
recs['book_id'] = recs['book_id'].astype(str)

In [28]:
top10_recs = recs['book_id'].value_counts().head(10)
top10_recs = top10_recs.index.values

In [29]:
top10_recs

array(['2657', '4671', '5470', '2767052', '5107', '3', '77203', '890',
       '7624', '38447'], dtype=object)

In [22]:
book_titles = pd.read_json('book_titles.json')

In [23]:
book_titles['book_id'] = book_titles['book_id'].astype(str)

In [25]:
book_titles.head()

,book_id,title,ratings,url,cover_image,mod_title
0,7327624,"The Unschooled Wizard (Sun Wolf and Starhawk, ...",140,https://www.goodreads.com/book/show/7327624-th...,https://images.gr-assets.com/books/1304100136m...,the unschooled wizard sun wolf and starhawk 12
1,6066819,Best Friends Forever,51184,https://www.goodreads.com/book/show/6066819-be...,https://s.gr-assets.com/assets/nophoto/book/11...,best friends forever
2,287141,The Aeneid for Boys and Girls,46,https://www.goodreads.com/book/show/287141.The...,https://s.gr-assets.com/assets/nophoto/book/11...,the aeneid for boys and girls
3,6066812,All's Fairy in Love and War (Avalon: Web of Ma...,98,https://www.goodreads.com/book/show/6066812-al...,https://images.gr-assets.com/books/1316637798m...,alls fairy in love and war avalon web of magic 8
4,287149,The Devil's Notebook,986,https://www.goodreads.com/book/show/287149.The...,https://images.gr-assets.com/books/1328768789m...,the devils notebook

In [31]:
book_titles[book_titles['book_id'].isin(top10_recs)]

,book_id,title,ratings,url,cover_image,mod_title
53027,77203,The Kite Runner,1848782,https://www.goodreads.com/book/show/77203.The_...,https://images.gr-assets.com/books/1484565687m...,the kite runner
284473,2767052,"The Hunger Games (The Hunger Games, #1)",4899965,https://www.goodreads.com/book/show/2767052-th...,https://images.gr-assets.com/books/1447303603m...,the hunger games the hunger games 1
396828,7624,Lord of the Flies,1638289,https://www.goodreads.com/book/show/7624.Lord_...,https://images.gr-assets.com/books/1327869409m...,lord of the flies
401395,5107,The Catcher in the Rye,2086945,https://www.goodreads.com/book/show/5107.The_C...,https://images.gr-assets.com/books/1398034300m...,the catcher in the rye
463463,4671,The Great Gatsby,2758812,https://www.goodreads.com/book/show/4671.The_G...,https://images.gr-assets.com/books/1490528560m...,the great gatsby
615314,5470,1984,2023937,https://www.goodreads.com/book/show/5470.1984,https://images.gr-assets.com/books/1348990566m...,1984
757376,38447,The Handmaid's Tale,648783,https://www.goodreads.com/book/show/38447.The_...,https://images.gr-assets.com/books/1498057733m...,the handmaids tale
790927,2657,To Kill a Mockingbird,3255518,https://www.goodreads.com/book/show/2657.To_Ki...,https://images.gr-assets.com/books/1361975680m...,to kill a mockingbird
840132,890,Of Mice and Men,1495516,https://www.goodreads.com/book/show/890.Of_Mic...,https://images.gr-assets.com/books/1437235233m...,of mice and men
878545,3,Harry Potter and the Sorcerer's Stone (Harry P...,4765497,https://www.goodreads.com/book/show/3.Harry_Po...,https://images.gr-assets.com/books/1474154022m...,harry potter and the sorcerers stone harry pot...

In [32]:
all_recs = recs['book_id'].value_counts()

In [34]:
all_recs = all_recs.to_frame().reset_index()

In [36]:
all_recs.columns = ['book_id', 'book_count']
all_recs

         book_id  book_count
0           2657         426
1           4671         422
2           5470         411
3        2767052         409
4           5107         402
...          ...         ...
196173    158180           1
196174   1199366           1
196175    488640           1
196176    381262           1
196177  27394467           1

[196178 rows x 2 columns]

In [37]:
all_recs = all_recs.merge(book_titles, how='inner', on='book_id')

In [38]:
all_recs.head()

,book_id,book_count,title,ratings,url,cover_image,mod_title
0,2657,426,To Kill a Mockingbird,3255518,https://www.goodreads.com/book/show/2657.To_Ki...,https://images.gr-assets.com/books/1361975680m...,to kill a mockingbird
1,4671,422,The Great Gatsby,2758812,https://www.goodreads.com/book/show/4671.The_G...,https://images.gr-assets.com/books/1490528560m...,the great gatsby
2,5470,411,1984,2023937,https://www.goodreads.com/book/show/5470.1984,https://images.gr-assets.com/books/1348990566m...,1984
3,2767052,409,"The Hunger Games (The Hunger Games, #1)",4899965,https://www.goodreads.com/book/show/2767052-th...,https://images.gr-assets.com/books/1447303603m...,the hunger games the hunger games 1
4,5107,402,The Catcher in the Rye,2086945,https://www.goodreads.com/book/show/5107.The_C...,https://images.gr-assets.com/books/1398034300m...,the catcher in the rye

In [39]:
all_recs['score'] = all_recs['book_count'] * (all_recs['book_count'] / all_recs['ratings'])

In [41]:
all_recs.sort_values('score', ascending=False).head(10)

,book_id,book_count,title,ratings,url,cover_image,mod_title,score
12,4408,319,East of Eden,3447,https://www.goodreads.com/book/show/4408.East_...,https://images.gr-assets.com/books/1323882457m...,east of eden,29.521613
242,31147619,107,Homegoing,697,https://www.goodreads.com/book/show/31147619-h...,https://images.gr-assets.com/books/1491119004m...,homegoing,16.426112
58,5996629,204,"Foundation (Foundation, #1)",5359,https://www.goodreads.com/book/show/5996629-fo...,https://images.gr-assets.com/books/1301851340m...,foundation foundation 1,7.765628
144,8132407,139,East of Eden,3006,https://www.goodreads.com/book/show/8132407-ea...,https://images.gr-assets.com/books/1328303315m...,east of eden,6.427478
3467,28170940,18,"Lethal White (Cormoran Strike, #4)",106,https://www.goodreads.com/book/show/28170940-l...,https://s.gr-assets.com/assets/nophoto/book/11...,lethal white cormoran strike 4,3.056604
337,28765183,88,Harry Potter and the Prisoner of Azkaban,3066,https://www.goodreads.com/book/show/28765183-h...,https://s.gr-assets.com/assets/nophoto/book/11...,harry potter and the prisoner of azkaban,2.525766
699,20494944,58,Lonesome Dove,1450,https://www.goodreads.com/book/show/20494944-l...,https://s.gr-assets.com/assets/nophoto/book/11...,lonesome dove,2.320000
438,5996631,77,"Foundation and Empire (Foundation, #2)",2568,https://www.goodreads.com/book/show/5996631-fo...,https://images.gr-assets.com/books/1305080024m...,foundation and empire foundation 2,2.308801
581,5996630,64,"Second Foundation (Foundation, #3)",2172,https://www.goodreads.com/book/show/5996630-se...,https://images.gr-assets.com/books/1305572510m...,second foundation foundation 3,1.885820
6958,34927828,10,The Great Alone,70,https://www.goodreads.com/book/show/34927828-t...,https://images.gr-assets.com/books/1501852384m...,the great alone,1.428571

In [43]:
popular_recs = all_recs[all_recs['book_count'] > 75].sort_values('score', ascending=False)

In [45]:
def make_clickable(link):
    return '<a target="_blank", href="{}">Goodreads</a>'.format(link)

def show_image(link):
    return '<img src="{}", width=50></img>'.format(link)

popular_recs[~popular_recs['book_id'].isin(liked_books)].head(10).style.format({'url': make_clickable, 'cover_image': show_image})